### ISSUE TITLE
count implementation is inefficient

### ISSUE THREAD

**Issue by lorenzhs** [MCGallaspy/dr_strangetemplate#2]
Your implementation of `count` is quite inefficient and neddlessly increases compile times. This would be better:

``` cpp
template <class... T>
using count = std::integral_constant<std::size_t, sizeof...(T)>;
```

(as remarked on Hacker News by `shin_lao`: https://news.ycombinator.com/item?id=12575366)

Additionally, you use `typedef` a lot in the first example - I think `using` should be preferred, as it's easier to read (and can be templated).

**Comment by MCGallaspy** [comment]
You're right that it uses more template instantiations than it needs to. The intrinsic `sizeof...` is undoubtedly faster, but I wonder by how much? I'll have to benchmark it! Regardless I've updated the examples with a different version using `sizeof...`.

**Comment by lorenzhs** [comment]
I think this is more of a "death by a thousand cuts" thing than a performance killer of its own. But thanks!
